#ifndef _ERRINFO_H_
#define _ERRINFO_H_

enum _ERR_NO{
	SUCCESS = 0,
	ERR,
	NULL_POINTER,
	NO_PRINTER,
	UNINITIAL,
	START_PAGE_FAILED,
	LOAD_IMG_FAILED,
	OPEN_DB_FAILED,
	CREATE_TABLE_FAILED,
	EXEC_SQL_FAILED,
	QUERY_DB_FAILED,
	INSERT_DB_FAILED,
	DELELTE_DB_FAILED,
	MODIFY_SQL_FAILED,
	UNKNOWN_PAGE_SIZE,
	CANNOT_NOT_NULL_STR,
};

#endif